apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: http-base
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: http-base:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      ref: demo
      uri: https://github.com/emcdowell2013/http-base
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: nodejs:12
        namespace: openshift
    type: Source
  successfulBuildsHistoryLimit: 5
  triggers:
  - github:
      secret: aVnja64UG5_AefMjQWt1
    type: GitHub
  - generic:
      secret: 4VFY9y_MiPwr0Bc8P4VH
    type: Generic
  - type: ConfigChange
  - imageChange:
      lastTriggeredImageID: image-registry.openshift-image-registry.svc:5000/openshift/nodejs@sha256:f9829b5c49ddf3b930f81ef8cbf516354035af2e4f88a9b9651a699957274bd1
    type: ImageChange
